version: "3.3"
services:
    mongodb:
        container_name: mongodb
        image: mongo:4.0.4
        volumes:
            - "./users.json:/users.json"
        ports: 
            - "27017:27017"
        restart: always


    nginx:
        container_name: nginx
        image: nginx
        ports:
            - "80:80"
        volumes:
            - "./index.html:/usr/share/nginx/html/index.html"
        restart: always
